name: CI 

on:
    push:
      branches: '*'
      tags:
        - 'v*'
    pull_request:
      branches: '*'

jobs:
  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    needs: [fmt]
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.74.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings  -W clippy::all -W clippy::pedantic

  build:
    needs: [fmt, clippy]
    name: Build 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.74.0
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run cargo check
        run: cargo build --all-features

  test:
    needs: [build]
    name: Tests 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.72.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Nextest 
        run: cargo nextest run --workspace --all-targets
